# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'SYKanZhihu' do
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'AMScrollingNavbar'
    pod 'EasyPull'
    pod 'Log'
end

