# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'SYKanZhihu' do
    pod 'Alamofire','~> 3.0'
    pod 'Kingfisher', '~> 2.0'
    pod 'AMScrollingNavbar','~> 2.0.1'
    pod 'EasyPull', '~> 1.1.0'
end

